// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityMenuSite.Data.Context;

#nullable disable

namespace UtilityMenuSite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.ApiToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Add-in Token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiTokens_Token");

                    b.HasIndex("UserId");

                    b.ToTable("ApiTokens", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("IX_AuditLogs_Action");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_AuditLogs_UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.BlogCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_BlogCategories_Slug");

                    b.ToTable("BlogCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "News",
                            Slug = "news",
                            SortOrder = 1
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "Tutorials",
                            Slug = "tutorials",
                            SortOrder = 2
                        },
                        new
                        {
                            CategoryId = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "Updates",
                            Slug = "updates",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.BlogPost", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_BlogPosts_CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UQ_BlogPosts_Slug");

                    b.ToTable("BlogPosts", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.ContactSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("SubmissionId");

                    b.HasIndex("IsResolved", "SubmittedAt")
                        .HasDatabaseName("IX_ContactSubmissions_IsResolved");

                    b.ToTable("ContactSubmissions", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Licence", b =>
                {
                    b.Property<Guid>("LicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenceKey")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxActivations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<string>("Signature")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LicenceId");

                    b.HasIndex("LicenceKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Licences_LicenceKey");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_Licences_SubscriptionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Licences_UserId");

                    b.ToTable("Licences", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.LicenceModule", b =>
                {
                    b.Property<Guid>("LicenceModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("LicenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.HasKey("LicenceModuleId");

                    b.HasIndex("LicenceId")
                        .HasDatabaseName("IX_LicenceModules_LicenceId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("LicenceId", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_LicenceModules");

                    b.ToTable("LicenceModules", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Machine", b =>
                {
                    b.Property<Guid>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("LicenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineFingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("MachineId");

                    b.HasIndex("LicenceId")
                        .HasDatabaseName("IX_Machines_LicenceId");

                    b.HasIndex("LicenceId", "MachineFingerprint")
                        .HasDatabaseName("IX_Machines_LicenceId_Fingerprint");

                    b.ToTable("Machines", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Module", b =>
                {
                    b.Property<Guid>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("ModuleId");

                    b.HasIndex("ModuleName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Modules_ModuleName");

                    b.ToTable("Modules", (string)null);

                    b.HasData(
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Get Last Row",
                            IsActive = true,
                            ModuleName = "GetLastRow",
                            SortOrder = 1,
                            Tier = "core"
                        },
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Get Last Column",
                            IsActive = true,
                            ModuleName = "GetLastColumn",
                            SortOrder = 2,
                            Tier = "core"
                        },
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Unhide Rows",
                            IsActive = true,
                            ModuleName = "UnhideRows",
                            SortOrder = 3,
                            Tier = "core"
                        },
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Advanced Data Tools",
                            IsActive = true,
                            ModuleName = "AdvancedData",
                            SortOrder = 4,
                            Tier = "pro"
                        },
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bulk Operations",
                            IsActive = true,
                            ModuleName = "BulkOperations",
                            SortOrder = 5,
                            Tier = "pro"
                        },
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Data Export",
                            IsActive = true,
                            ModuleName = "DataExport",
                            SortOrder = 6,
                            Tier = "pro"
                        },
                        new
                        {
                            ModuleId = new Guid("11111111-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "SQL Builder",
                            IsActive = true,
                            ModuleName = "SqlBuilder",
                            SortOrder = 7,
                            Tier = "pro"
                        });
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.StripeCustomer", b =>
                {
                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("StripeCustomerId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_StripeCustomers_UserId");

                    b.ToTable("StripeCustomers", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.StripeWebhookEvent", b =>
                {
                    b.Property<Guid>("WebhookEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("StripeEventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("WebhookEventId");

                    b.HasIndex("StripeEventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_StripeWebhookEvents_StripeEventId");

                    b.ToTable("StripeWebhookEvents", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CurrentPeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GracePeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TrialStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("StripeCustomerId")
                        .HasDatabaseName("IX_Subscriptions_StripeCustomerId");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscriptions_StripeSubscriptionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Subscriptions_UserId");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.UsageEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("EventData")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LicenceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("LicenceId");

                    b.HasIndex("MachineId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_UsageEvents_EventType");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_UsageEvents_UserId");

                    b.ToTable("UsageEvents", (string)null);
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("ApiToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("JobRole")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisation")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProfileCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("UsageInterests")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("ApiToken")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_ApiToken");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_IdentityId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilityMenuSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.ApiToken", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.User", "User")
                        .WithMany("ApiTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ApiTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.AuditLog", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_AuditLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.BlogPost", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.User", "Author")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_BlogPosts_Users");

                    b.HasOne("UtilityMenuSite.Data.Models.BlogCategory", "Category")
                        .WithMany("BlogPosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlogPosts_Categories");

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Licence", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.Subscription", "Subscription")
                        .WithMany("Licences")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Licences_Subscriptions");

                    b.HasOne("UtilityMenuSite.Data.Models.User", "User")
                        .WithMany("Licences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Licences_Users");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.LicenceModule", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.Licence", "Licence")
                        .WithMany("LicenceModules")
                        .HasForeignKey("LicenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LicenceModules_Licences");

                    b.HasOne("UtilityMenuSite.Data.Models.Module", "Module")
                        .WithMany("LicenceModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LicenceModules_Modules");

                    b.Navigation("Licence");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Machine", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.Licence", "Licence")
                        .WithMany("Machines")
                        .HasForeignKey("LicenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Machines_Licences");

                    b.Navigation("Licence");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.StripeCustomer", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.User", "User")
                        .WithOne("StripeCustomer")
                        .HasForeignKey("UtilityMenuSite.Data.Models.StripeCustomer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StripeCustomers_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Subscription", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.StripeCustomer", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("StripeCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilityMenuSite.Data.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.UsageEvent", b =>
                {
                    b.HasOne("UtilityMenuSite.Data.Models.Licence", "Licence")
                        .WithMany("UsageEvents")
                        .HasForeignKey("LicenceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UsageEvents_Licences");

                    b.HasOne("UtilityMenuSite.Data.Models.Machine", "Machine")
                        .WithMany("UsageEvents")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UsageEvents_Machines");

                    b.HasOne("UtilityMenuSite.Data.Models.Module", "Module")
                        .WithMany("UsageEvents")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UsageEvents_Modules");

                    b.HasOne("UtilityMenuSite.Data.Models.User", "User")
                        .WithMany("UsageEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UsageEvents_Users");

                    b.Navigation("Licence");

                    b.Navigation("Machine");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.BlogCategory", b =>
                {
                    b.Navigation("BlogPosts");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Licence", b =>
                {
                    b.Navigation("LicenceModules");

                    b.Navigation("Machines");

                    b.Navigation("UsageEvents");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Machine", b =>
                {
                    b.Navigation("UsageEvents");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Module", b =>
                {
                    b.Navigation("LicenceModules");

                    b.Navigation("UsageEvents");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.StripeCustomer", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.Subscription", b =>
                {
                    b.Navigation("Licences");
                });

            modelBuilder.Entity("UtilityMenuSite.Data.Models.User", b =>
                {
                    b.Navigation("ApiTokens");

                    b.Navigation("AuditLogs");

                    b.Navigation("BlogPosts");

                    b.Navigation("Licences");

                    b.Navigation("StripeCustomer");

                    b.Navigation("Subscriptions");

                    b.Navigation("UsageEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
